# Generated by Django 6.0.3 on 2026-04-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_aboutpagemedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
